// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// hapr_mle_survival_nll_split_grad_cpp
Rcpp::List hapr_mle_survival_nll_split_grad_cpp(const arma::vec& params, const arma::vec& event_time, const arma::vec& avg_linpred_event, const arma::mat& X_w_event, const arma::vec& censor_time, const arma::vec& avg_linpred_censor, const arma::mat& X_w_censor, double post_c, int model_type, bool use_openmp);
RcppExport SEXP _hapr_hapr_mle_survival_nll_split_grad_cpp(SEXP paramsSEXP, SEXP event_timeSEXP, SEXP avg_linpred_eventSEXP, SEXP X_w_eventSEXP, SEXP censor_timeSEXP, SEXP avg_linpred_censorSEXP, SEXP X_w_censorSEXP, SEXP post_cSEXP, SEXP model_typeSEXP, SEXP use_openmpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type event_time(event_timeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type avg_linpred_event(avg_linpred_eventSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X_w_event(X_w_eventSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type censor_time(censor_timeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type avg_linpred_censor(avg_linpred_censorSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X_w_censor(X_w_censorSEXP);
    Rcpp::traits::input_parameter< double >::type post_c(post_cSEXP);
    Rcpp::traits::input_parameter< int >::type model_type(model_typeSEXP);
    Rcpp::traits::input_parameter< bool >::type use_openmp(use_openmpSEXP);
    rcpp_result_gen = Rcpp::wrap(hapr_mle_survival_nll_split_grad_cpp(params, event_time, avg_linpred_event, X_w_event, censor_time, avg_linpred_censor, X_w_censor, post_c, model_type, use_openmp));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hapr_hapr_mle_survival_nll_split_grad_cpp", (DL_FUNC) &_hapr_hapr_mle_survival_nll_split_grad_cpp, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_hapr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
