# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hapr_mle_lm_nll_cpp <- function(params, y, avg_linpred, X_w, post_c) {
    .Call(`_hapr_hapr_mle_lm_nll_cpp`, params, y, avg_linpred, X_w, post_c)
}

