# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hapr_mle_survival_nll_split_grad_cpp <- function(params, event_time, avg_linpred_event, X_w_event, censor_time, avg_linpred_censor, X_w_censor, post_c, model_type, use_openmp) {
    .Call(`_hapr_hapr_mle_survival_nll_split_grad_cpp`, params, event_time, avg_linpred_event, X_w_event, censor_time, avg_linpred_censor, X_w_censor, post_c, model_type, use_openmp)
}

